In [13]:
import numpy as np
ar1=np.array([1,2,3])
ar2=np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

print(ar1*2)
print(ar1+ar1)

import numpy as np
ar3=np.arange(12).reshape(3,4)
print(ar3)

matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2))




[1 2 3]
[[1 2 3]
 [4 5 6]]
[2 4 6]
[2 4 6]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]


In [12]:
import numpy as np
data=np.random.normal(0,1,100)
print(f'mean:{data.mean()} , SD:{data.std()}')

mean:0.07675923385507381 , SD:0.9659356124500862


In [2]:
import pandas as pd
import numpy as np
data={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,35,40],
    'Salary':[50000,60000,70000,80000]
}
df=pd.DataFrame(data)
print(df)

print(df.head(2))
print(df.describe())
print(df['Age'].mean())

print(df[df['Age']>30])
print(df.loc[1:2, ['Name','Salary']])

df_with_nan=pd.DataFrame({
    'A':[1,2,np.nan,4],
    'B':[5,np.nan,np.nan,8]
})
print(df_with_nan.fillna(value=0))
print(df_with_nan.dropna())

df['Department']=['HR','Tech','Tech','HR']
print(df.groupby('Department')[['Age', 'Salary']].mean())

df2=pd.DataFrame({
    'Name':['Alice','Bob','Eve'],
    'Bonus':[2000,1500,3000]

})
print(pd.merge(df,df2,on='Name', how='left'))

date_rng=pd.date_range(start='1/1/2023', end='1/10/2023',freq='D')
ts=pd.DataFrame(date_rng,columns=['date'])
ts['value']=np.random.randint(0,100,size=(len(date_rng)))
ts.set_index('date',inplace=True)
print(ts.resample('3D').mean())

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000
             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000
32.5
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000
      Name  Salary
1      Bob   60000
2  Charlie   70000
     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0
     A    B
0  1.0  5.0
3  4.0  8.0
             Age   Salary
Department               
HR          32.5  65000.0
Tech        32.5  65000.0
      Name  Age  Salary Department   Bonus
0    Alice   25   50000         HR  2000.0
1      Bob   30   60000       Tech  1500.0
2  Charlie   35   70000       Tech     NaN
3    David   40   80000      